### ISSUE TITLE
Loading without X-Forwarding

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/Bug-Reports#6]
`hutch-python` can't load without X-Forwarding. Seems like we shouldn't get stuck until we actually try and load a graphic.

https://pswww.slac.stanford.edu/apps/portal/index.php?exper_id=794&app=elog:search&params=message:386991

**Comment by ZLLentz** [comment]
This is news to me, since it loads in Travis with no display at all. The try/except block here was supposed to save it:

https://github.com/pcdshub/hutch-python/blob/0c0c897b313f9dbad46cc091c449ab86d37cfc9f/hutch_python/load_conf.py#L205-L209

Perhaps a different line is erroring, or for our systems its core dumping instead of raising a `RuntimeError` (?). This is worth investigating. It will probably require careful inspection of the environment to set a global `use_display` variable.

**Comment by teddyrendahl** [comment]
I think it is this: https://github.com/pcdshub/hutch-python/blob/0c0c897b313f9dbad46cc091c449ab86d37cfc9f/hutch_python/cli.py#L131-L132.

No idea why this doesn't break Travis

**Comment by ZLLentz** [comment]
I would have expected travis to fail on https://github.com/pcdshub/hutch-python/blob/0c0c897b313f9dbad46cc091c449ab86d37cfc9f/hutch_python/tests/test_tstpython.py#L28-L29 with a `CalledProcessError`
